### ISSUE TITLE
All passing of environment variables into docker-compose

### ISSUE THREAD

**Issue by sidney-simmons** [sidney-simmons/gradle-plugin-docker#36]
Allow passing of environment variables into the docker-compose.yml file.  For example:

```
docker {
    environment('POSTGRES_USER', 'my-user')
    environment('POSTGRES_PASSWORD', 'my-password')
}
```
```
version: '3'
services:
    postgres:
        image: postgres:11.5-alpine
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password1}
    boot:
        build: .
        ports:
        - 8001:8001
        depends_on:
        - postgres
```
